### ISSUE TITLE
dagger-android

### ISSUE THREAD

**Issue by danielflores108** [erikcaffrey/Android-Architecture-Components-Kotlin#12]
Hola Erick, planeas actualizar a dagger-android? o lo harás en un nuevo repo?

**Comment by erikjhordan-rey** [comment]
@danielflores108 El proyecto ya tiene dagger, no veo creo que actualice a Dagger-Android, dagger resuelve los problemas que necesito para este proyecto, querías ver algo en especifico?

**Comment by danielflores108** [comment]
Básicamente saber qué tanto cambia la implementación, he estado investigando y lo más "drástico" es que ya no pasas los módulos en Application, el manejo de subcomponentes, builders y las anotaciones.

Por ejemplo en tu AppModule tienes un Application y así provees el contexto. Lo que hice yo fue crear un @Component.Builder en mi AppComponent, de esta forma proveo el contexto desde el AppModule pero no declaré un constructor de AppModule que reciba Application. Lo cual no sé si esté bien, sirve, inyecta y todo, pero no sé si sería LA forma de hacerlo.

**Comment by erikjhordan-rey** [comment]
Claro fue creado con la finalidad de facilitar la inyección de dependencias un más en el caso de android es por eso que se han creado esas clases de dagger-android y eso es por que una clase no debería saber nada de como se inyecta, por ese motivo ya no se pasa nada de módulos en tu grafo ; quizás haga un proyecto aplicando estas classes `dagger-android` pero este no creo que lo migre, gracias por tus comentarios y cuando este listo lo publicaré.
