### ISSUE TITLE
It can be a private field

### ISSUE THREAD

**Issue by mniami** [erikcaffrey/Android-Architecture-Components-Kotlin#15]
https://github.com/erikcaffrey/Android-Architecture-Components-Kotlin/blob/643edf4de2921fe287fe1242edeee7937cb87607/app/src/main/kotlin/erikjhordanrey/android_kotlin_devises/data/repository/CurrencyRepository.kt#L39

**Comment by erikjhordan-rey** [comment]
is used in VM, thanks
